import "./globals.css";
import { Navbar } from "@components/_common/navbar/Navbar.jsx";
import { Footer } from "@components/_common/footer/Footer.jsx";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Autoescuela Rayán",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" type="image/x-icon" href="favicon.ico"></link>
        <script src="https://cdn.lordicon.com/lordicon.js"></script>
      </head>
      <body className={inter.className} suppressHydrationWarning>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
